/*

 MAP2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : D:\Assorted Apps\Gameboy Dev\tiles\borders.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define cgbmap1Width 20
#define cgbmap1Height 18
#define cgbmap1Bank 0

extern unsigned char cgbmap1[];

/* End of MAP2.H */
